### ISSUE TITLE
fli-docker wont work with zpools or token other than `chq` and `/root/<token>`

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/fli-docker#45]
zpool is hard coded here

https://github.com/ClusterHQ/fli-docker/blob/master/utils/utils.go#L55

**Comment by wallnerryan** [comment]
@pcgeek86 this is why `fli-docker snapshot -push` was failing with your `denverimaging` zpool, will add a patch that will use the zpool from `fli info` output (`ZPOOL:           chq`).

**Comment by wallnerryan** [comment]
As another note, the token file is not always in `/root` so that same concern about mounting in that to the container is there.

 I wonder if it make more sense to have have the user setup their alias, and just cal `fli` from `exec.Command()` with that assumption.

Or, the other option, is to make this configurable, which we sort of do with `-e` and `-t` but it doesnt translate to the fli docker command assumptions. 

I may choose the first option as the approach if that works

**Comment by pcgeek86** [comment]
@wallnerryan Another option would be to use an environment variable, but both Fli and Fli Docker would have to agree upon that.
